# Generated by Django 5.2.4 on 2025-07-27 12:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
                ('category', models.CharField(max_length=50)),
                ('mime_type', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_input_supported', models.BooleanField(default=True)),
                ('is_output_supported', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'file_formats',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BatchConversionJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('conversion_options', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('webhook_url', models.URLField(blank=True)),
                ('webhook_sent', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_jobs', to=settings.AUTH_USER_MODEL)),
                ('output_format', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conversions.fileformat')),
            ],
            options={
                'db_table': 'batch_conversion_jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConversionJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('input_file', models.FileField(upload_to='input_files/%Y/%m/%d/')),
                ('output_file', models.FileField(blank=True, null=True, upload_to='output_files/%Y/%m/%d/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('priority', models.IntegerField(choices=[(1, 'Low'), (2, 'Normal'), (3, 'High'), (4, 'Critical')], default=2)),
                ('progress_percentage', models.FloatField(default=0.0)),
                ('conversion_options', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('max_retries', models.IntegerField(default=3)),
                ('webhook_url', models.URLField(blank=True)),
                ('webhook_sent', models.BooleanField(default=False)),
                ('input_file_size', models.BigIntegerField(blank=True, null=True)),
                ('output_file_size', models.BigIntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversion_jobs', to=settings.AUTH_USER_MODEL)),
                ('input_format', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_conversions', to='conversions.fileformat')),
                ('output_format', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='output_conversions', to='conversions.fileformat')),
            ],
            options={
                'db_table': 'conversion_jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConversionQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_conversions_limit', models.IntegerField(default=100)),
                ('monthly_conversions_used', models.IntegerField(default=0)),
                ('monthly_storage_limit_mb', models.IntegerField(default=1000)),
                ('monthly_storage_used_mb', models.IntegerField(default=0)),
                ('last_reset_date', models.DateField(auto_now_add=True)),
                ('is_premium', models.BooleanField(default=False)),
                ('premium_expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quota', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'conversion_quotas',
            },
        ),
        migrations.CreateModel(
            name='ConversionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_format', models.CharField(max_length=10)),
                ('output_format', models.CharField(max_length=10)),
                ('file_size_bytes', models.BigIntegerField()),
                ('processing_time_seconds', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversion_history', to=settings.AUTH_USER_MODEL)),
                ('conversion_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conversions.conversionjob')),
            ],
            options={
                'db_table': 'conversion_history',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='conversion__user_id_49cd63_idx'), models.Index(fields=['input_format', 'output_format'], name='conversion__input_f_e51566_idx')],
            },
        ),
        migrations.CreateModel(
            name='BatchJobFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('batch_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individual_jobs', to='conversions.batchconversionjob')),
                ('conversion_job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='batch_file', to='conversions.conversionjob')),
            ],
            options={
                'db_table': 'batch_job_files',
                'ordering': ['order'],
                'unique_together': {('batch_job', 'order')},
            },
        ),
        migrations.AddIndex(
            model_name='conversionjob',
            index=models.Index(fields=['user', 'status'], name='conversion__user_id_801a6f_idx'),
        ),
        migrations.AddIndex(
            model_name='conversionjob',
            index=models.Index(fields=['created_at'], name='conversion__created_0a221f_idx'),
        ),
        migrations.AddIndex(
            model_name='conversionjob',
            index=models.Index(fields=['status', 'priority'], name='conversion__status_463516_idx'),
        ),
    ]
