# Generated by Django 5.2.4 on 2025-07-27 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversionjob',
            name='webhook_url',
            field=models.URLField(blank=True),
        ),
    ]
